src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $genre;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    #[ORM\Column(type: 'string', length: 4048, nullable: true)]
    private $description;

    #[ORM\ManyToMany(targetEntity: Library::class, mappedBy: 'books')]
    private $libraries;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $poster_url;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $pdf_url;

    #[ORM\OneToMany(mappedBy: 'book', targetEntity: Order::class)]
    private $orders;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $author;

    public function __construct()
    {
        $this->libraries = new ArrayCollection();
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, Library>
     */
    public function getLibraries(): Collection
    {
        return $this->libraries;
    }

    public function addLibrary(Library $library): self
    {
        if (!$this->libraries->contains($library)) {
            $this->libraries[] = $library;
            $library->addBook($this);
        }

        return $this;
    }

    public function removeLibrary(Library $library): self
    {
        if ($this->libraries->removeElement($library)) {
            $library->removeBook($this);
        }

        return $this;
    }

    public function getPosterUrl(): ?string
    {
        return $this->poster_url;
    }

    public function setPosterUrl(?string $poster_url): self
    {
        $this->poster_url = $poster_url;

        return $this;
    }

    public function getPdfUrl(): ?string
    {
        return $this->pdf_url;
    }

    public function setPdfUrl(string $pdf_url): self
    {
        $this->pdf_url = $pdf_url;

        return $this;
    }

    /**
     * @return Collection<int, Order>
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setBook($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getBook() === $this) {
                $order->setBook(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $status;

    #[ORM\Column(type: 'string', length: 255)]
    private $book_format;

    #[ORM\Column(type: 'date')]
    private $date_create;

    #[ORM\ManyToOne(targetEntity: Reader::class, inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private $user;

    #[ORM\ManyToOne(targetEntity: Book::class, inversedBy: 'orders')]
    private $book;

    #[ORM\ManyToOne(targetEntity: Library::class, inversedBy: 'orders')]
    #[ORM\JoinColumn(nullable: false)]
    private $library;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getBookFormat(): ?string
    {
        return $this->book_format;
    }

    public function setBookFormat(string $book_format): self
    {
        $this->book_format = $book_format;

        return $this;
    }

    public function getDateCreate(): ?\DateTimeInterface
    {
        return $this->date_create;
    }

    public function setDateCreate(\DateTimeInterface $date_create): self
    {
        $this->date_create = $date_create;

        return $this;
    }

    public function getUser(): ?Reader
    {
        return $this->user;
    }

    public function setUser(?Reader $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getBook(): ?Book
    {
        return $this->book;
    }

    public function setBook(?Book $book): self
    {
        $this->book = $book;

        return $this;
    }

    public function getLibrary(): ?Library
    {
        return $this->library;
    }

    public function setLibrary(?Library $library): self
    {
        $this->library = $library;

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('status',ChoiceType::class, [
                'label' => 'Статус заказа',
                'choices'  => [
                    'Не подтвержден' => 'not confirmed',
                    'Подтвержден' => 'confirmed'
                ],
                ])
            ->add('date_create', DateType::class, [
                'label' => 'Дата создания/подтверждения:',
                'attr' => array('class' => 'row g-3', 'style'=>"margin: 10px 0 10px 0"),
                'widget' => 'single_text'
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
            'fio' => 'Не указано'
        ]);
        $resolver->setAllowedTypes('fio', 'string');
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use Knp\Snappy\Pdf;
use App\Entity\Book;
use App\Entity\User;
use App\Entity\Order;
use App\Form\OrderType;
use App\Entity\Librarian;
use App\Repository\BookRepository;
use App\Repository\UserRepository;
use App\Repository\OrderRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/order')]
class OrderController extends AbstractController
{
    #[Route('/', name: 'app_order_index', methods: ['GET'])]
    public function index(Request $request, OrderRepository $orderRepository, ManagerRegistry $doctrine): Response
    {
        $order = new Order();
        $entityManager = $doctrine->getManager();
        $session = $request->getSession();
        $email = $session->get(Security::LAST_USERNAME) ?? null;
        $user=$entityManager->getRepository(User::class)->findOneByEmail($email);
        $librarian = $user->getLibrarian();
        $liba;
        // те заказы у которых юзер айди
        // var_dump($user->getRoles());
        // die();
        if($user->getRoles()===array("ROLE_ADMIN", "ROLE_USER")){
            $orders = $orderRepository->findAll();
            $liba['name'] = 'все библиотеки';
        } else {
            $liba = $librarian->getLibrary();
            $orders = $orderRepository->findByLibrary($liba);
        }
        $books = array();
        //$orders = $orderRepository->findAll();
        krsort($orders);
        $users = array();
        foreach ($orders as $order){
            $user = $order->getUser()->getUser();
            $books[$order->getId()] = $order->getBook()->getName();
            $users[$order->getId()] = $user->getLastname() . ' ' . $user->getFirstname(). ' ' . $user->getPatronimic();
        }

        return $this->render('order/index.html.twig', [
            'orders' => $orders,
            'users' => $users,
            'books' => $books,
            'library' => $liba
        ]);
    }

    
    #[Route('/report-good-status', name: 'app_report_status', methods: ['GET'])]
    public function makeReportByStatus(Request $request, OrderRepository $orderRepository, ManagerRegistry $doctrine, Pdf $knpSnappyPdf): Response
    {   
        $entityManager = $doctrine->getManager();
        $session = $request->getSession();
        $email = $session->get(Security::LAST_USERNAME) ?? null;
        $user=$entityManager->getRepository(User::class)->findOneByEmail($email);
        $librarian = $user->getLibrarian();
        
        // те заказы у которых юзер айди
        $orders = $orderRepository->findByStatus("confirmed");
        $books = array();
        //$orders = $orderRepository->findAll();
        krsort($orders);
        $users = array();
        foreach ($orders as $order){
            $user = $order->getUser()->getUser();
            $books[$order->getId()] = $order->getBook()->getName();
            $users[$order->getId()] = $user->getLastname() . ' ' . $user->getFirstname(). ' ' . $user->getPatronimic();
        }
        $html =$this->renderView('order/order_report_good_status.html.twig', [
            'orders' => $orders,
            'users' => $users,
            'books' => $books,
            'library' => $librarian->getLibrary()
        ]);
        $knpSnappyPdf->setOption('encoding', 'utf-8');
            return new PdfResponse(
                $knpSnappyPdf->getOutputFromHtml($html),
                'Report.pdf',
            );
    }

    #[Route('/report-bad-status', name: 'app_report_status_bad', methods: ['GET'])]
    public function makeReportByBadStatus(Request $request, OrderRepository $orderRepository, ManagerRegistry $doctrine, Pdf $knpSnappyPdf): Response
    {   
        $entityManager = $doctrine->getManager();
        $session = $request->getSession();
        $email = $session->get(Security::LAST_USERNAME) ?? null;
        $user=$entityManager->getRepository(User::class)->findOneByEmail($email);
        $librarian = $user->getLibrarian();
        
        // те заказы у которых юзер айди
        $orders = $orderRepository->findByStatus("not confirmed");
        $books = array();
        //$orders = $orderRepository->findAll();
        krsort($orders);
        $users = array();
        foreach ($orders as $order){
            $user = $order->getUser()->getUser();
            $books[$order->getId()] = $order->getBook()->getName();
            $users[$order->getId()] = $user->getLastname() . ' ' . $user->getFirstname(). ' ' . $user->getPatronimic();
        }
        $html =$this->renderView('order/order_report_good_status.html.twig', [
            'orders' => $orders,
            'users' => $users,
            'books' => $books,
            'library' => $librarian->getLibrary()
        ]);
        $knpSnappyPdf->setOption('encoding', 'utf-8');
            return new PdfResponse(
                $knpSnappyPdf->getOutputFromHtml($html),
                'Report.pdf',
            );
    }

    #[Route('/reportByDays', name: 'app_report_days', methods: ['GET'])]
    public function makeReportByDays(Request $request, OrderRepository $orderRepository, ManagerRegistry $doctrine, Pdf $knpSnappyPdf): Response
    {
        $entityManager = $doctrine->getManager();
        $session = $request->getSession();
        $email = $session->get(Security::LAST_USERNAME) ?? null;
        $user=$entityManager->getRepository(User::class)->findOneByEmail($email);
        $librarian = $user->getLibrarian();
        
        // те заказы у которых юзер айди
        //$today = time();

        $today = new \DateTime();
        //$today = date("y-m-d");
        $orders = $orderRepository->findBy(['date_create'=>$today]);//$orderRepository->findByStatus("not confirmed");
        $books = array();
        //$orders = $orderRepository->findAll();
        krsort($orders);
        $users = array();
        foreach ($orders as $order){
            $user = $order->getUser()->getUser();
            $books[$order->getId()] = $order->getBook()->getName();
            $users[$order->getId()] = $user->getLastname() . ' ' . $user->getFirstname(). ' ' . $user->getPatronimic();
        }
        $html =$this->renderView('order/order_report_good_status.html.twig', [
            'orders' => $orders,
            'users' => $users,
            'books' => $books,
            'library' => $librarian->getLibrary()
        ]);
        $knpSnappyPdf->setOption('encoding', 'utf-8');
            return new PdfResponse(
                $knpSnappyPdf->getOutputFromHtml($html),
                'Report.pdf',
            );
    }

    #[Route('/reportByWeek', name: 'app_report_week', methods: ['GET'])]
    public function makeReportByWeek(Request $request, OrderRepository $orderRepository, ManagerRegistry $doctrine, Pdf $knpSnappyPdf): Response
    {
        $entityManager = $doctrine->getManager();
        $session = $request->getSession();
        $email = $session->get(Security::LAST_USERNAME) ?? null;
        $user=$entityManager->getRepository(User::class)->findOneByEmail($email);
        $librarian = $user->getLibrarian();
        
        // те заказы у которых юзер айди
        //$today = time();

        $weekStart = new \DateTime("-7 days");
        $weekEnd = new \DateTime();
        //$today = date("y-m-d");
        $orders = $orderRepository->getOrderByDataInterval($weekStart, $weekEnd);//$orderRepository->findByStatus("not confirmed");
        $books = array();
        //$orders = $orderRepository->findAll();
        krsort($orders);
        $users = array();
        foreach ($orders as $order){
            $user = $order->getUser()->getUser();
            $books[$order->getId()] = $order->getBook()->getName();
            $users[$order->getId()] = $user->getLastname() . ' ' . $user->getFirstname(). ' ' . $user->getPatronimic();
        }
        $html =$this->renderView('order/order_report_good_status.html.twig', [
            'orders' => $orders,
            'users' => $users,
            'books' => $books,
            'library' => $librarian->getLibrary()
        ]);
        $knpSnappyPdf->setOption('encoding', 'utf-8');
            return new PdfResponse(
                $knpSnappyPdf->getOutputFromHtml($html),
                'Report.pdf',
            );
    }

    #[Route('/reportByMonth', name: 'app_report_month', methods: ['GET'])]
    public function makeReportByMonth(Request $request, OrderRepository $orderRepository, ManagerRegistry $doctrine, Pdf $knpSnappyPdf): Response
    {
        $entityManager = $doctrine->getManager();
        $session = $request->getSession();
        $email = $session->get(Security::LAST_USERNAME) ?? null;
        $user=$entityManager->getRepository(User::class)->findOneByEmail($email);
        $librarian = $user->getLibrarian();
        
        // те заказы у которых юзер айди
        //$today = time();

        $weekStart = new \DateTime("-30 days");
        $weekEnd = new \DateTime();
        //$today = date("y-m-d");
        $orders = $orderRepository->getOrderByDataInterval($weekStart, $weekEnd);//$orderRepository->findByStatus("not confirmed");
        $books = array();
        //$orders = $orderRepository->findAll();
        krsort($orders);
        $users = array();
        foreach ($orders as $order){
            $user = $order->getUser()->getUser();
            $books[$order->getId()] = $order->getBook()->getName();
            $users[$order->getId()] = $user->getLastname() . ' ' . $user->getFirstname(). ' ' . $user->getPatronimic();
        }
        $html =$this->renderView('order/order_report_good_status.html.twig', [
            'orders' => $orders,
            'users' => $users,
            'books' => $books,
            'library' => $librarian->getLibrary()
        ]);

templates/order/_delete_form.html.twig
<form method="post" action="{{ path('app_order_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn btn-outline-dark" style="margin: 0 0 500px 0">Удалить</button>
</form>

templates/order/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary mb-3">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/order/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Order{% endblock %}

{% block body %}
    <h3>Изменение заказа</h3>
<div class="input-group">
    {{ include('order/_form.html.twig', {'button_label': 'Сохранить изменения'}) }}
</d>
<div class="input-group">
{{ include('order/_delete_form.html.twig') }}
</d>
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Заказы</h1>
    {% if is_granted('ROLE_LIBRARIAN') and not is_granted('ROLE_ADMIN')%}
    <h3>{{library.name}}</h3>
    <a href="{{ path('app_report_status') }}" class="btn btn-outline-dark">Отчет о подтвержденных заказах</a>
    <a href="{{ path('app_report_status_bad') }}" class="btn btn-outline-dark">Отчет о неподтвержденных заказах</a>
    <a href="{{ path('app_report_days') }}" class="btn btn-outline-dark">Отчет о заказах за день</a>
    <a href="{{ path('app_report_week') }}" class="btn btn-outline-dark">Отчет о заказах за неделю</a>
    <a href="{{ path('app_report_month') }}" class="btn btn-outline-dark">Отчет о заказах за месяц</a>
    {% endif %}
    <table class="table">
        <thead>
            <tr>
            {% if is_granted('ROLE_LIBRARIAN') or is_granted('ROLE_ADMIN')%}
                <th>Заказчик</th>
                {% endif %}
                <th>Статус заказа</th>
                <th>Книга</th>
                <th>Дата создания/подтверждения</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
            {% if is_granted('ROLE_LIBRARIAN') or is_granted('ROLE_ADMIN')%}
                <td>{{ users[order.id] }}</td>
                {% endif %}
                <td>
                   {% if order.status == 'confirmed'%}
                    Подтвержден
                    {% else %}
                    Ожидает подтверждения работником библиотеки 
                    {% endif %}
                    </td>
                <td> {{ books[order.id] }} </td>
                <td>{{ order.dateCreate ? order.dateCreate|date('Y-m-d') : '' }}
                <td>
                    <a href="{{ path('app_order_show', {'id': order.id}) }}" class="btn btn-outline-dark">Подробнее</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">У Вас пока нет заказов</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/order/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Order{% endblock %}

{% block body %}
    <h3>Страница не найдена</h1>
{% endblock %}

templates/order/order_report_good_status.html.twig
{% block body %}
    <h1>Заказы</h1>
    {% if is_granted('ROLE_LIBRARIAN')%}
    <h3>{{library.name}}</h3>
    {% endif %}
    <table class="table">
        <thead>
            <tr>
            {% if is_granted('ROLE_LIBRARIAN')%}
                <th>Заказчик</th>
                {% endif %}
                <th>Статус заказа</th>
                <th>Книга</th>
                <th>Дата создания/подтверждения</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
            {% if is_granted('ROLE_LIBRARIAN')%}
                <td>{{ users[order.id] }}</td>
                {% endif %}
                <td>
                   {% if order.status == 'confirmed'%}
                    Подтвержден
                    {% else %}
                    Ожидает подтверждения работником библиотеки 
                    {% endif %}
                    </td>
                <td> {{ books[order.id] }} </td>
                <td>{{ order.dateCreate ? order.dateCreate|date('Y-m-d') : '' }}
            </tr>
        {% else %}
            <tr>
                <td colspan="5">У Вас пока нет заказов</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    <h1>Заказ от {{ order.dateCreate ? order.dateCreate|date('Y-m-d') : '' }}</h1>
    <p>Статус:
    {% if order.status == 'confirmed'%}
    Подтвержден</p>
    {% else %}
    Ожидает подтверждения работником библиотеки </p>
    {% endif %}
{% if is_granted('ROLE_LIBRARIAN')%}
    <p>Заказчик: {{fio}}</p>
    <p>Почта заказчика: {{user.email}}</p>
    <p>Телефон заказчика: {{user.phone}}</p>
{% endif %}
    <div class="row g-3">
        <fieldset aria-label="Disabled fieldset example">
          <div class="mb-3">
                <h1>{{ book.name }}</h1>
                <label class="form-label"> {{ book.author }}</label>
            </div>
            <div class="card mb-3" style="max-width: 880px;">
              <div class="row g-0">
                <div class="col-md-4">
                  <img src="{{ book.posterUrl }}" class="img-fluid rounded-start" alt=" Обложка отсутствует" style='height: 200px;'>
                </div>
                <div class="col-md-8">
                  <div class="card-body">
                    <p class="card-text">{{ book.description }}</p>
                    <p class="card-text"><small class="text-muted">{{ book.genre }}</small></p>
                        <div class="mb-3">
                        <p class="card-text"> {{ library.name }}</p>
                       </div>
                    </div>
                 </div>
             </div>
         </div>
      </fieldset>
    </div>
<a href="{{ path('app_book_index') }}" class="btn btn-primary my-2">Вернуться к поиску книг</a>
{% if order.status == 'confirmed' and not is_granted('ROLE_LIBRARIAN')%}
    <a href="{{ book.pdfUrl }}" class="btn btn-primary my-2">Читать онлайн</a>
{% endif %}
{% if is_granted('ROLE_LIBRARIAN')%}
<a href="{{ path('app_order_index') }}" class="btn btn-primary my-2">Вернуться к списку заказов</a>
<a href="{{ path('app_order_edit', {'id': order.id}) }}" class="btn btn-primary my-2">Изменить</a>
{% endif %}
<br><br><br><br><br>
{% endblock %}